# Generated by Django 3.2.9 on 2021-12-17 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0003_forum_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Forum',
        ),
    ]
